site_name: KSML
site_author: Axual
site_description: Documentation for the KSML project
site_dir: _site
theme: mkdocs
#theme: readthedocs

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Quick start: quick-start.md
  - Reference:
    - Streams: reference-docs/streams.md
    - Pipelines: reference-docs/pipelines.md
    - Types: reference-docs/types.md
    - Notations: reference-docs/notations.md
    - Operstions: reference-docs/operations.md
    - Functions: reference-docs/functions.md
    - Stores: reference-docs/stores.md
    - Runners: reference-docs/runners.md
  - Language specification: ksml-language-spec.md
  - Release Notes: release-notes.md
