pipelines:
  main:
    from: sensor_source
    via:
    - type: transformValue
      mapper:
        resultType: json
        code: 'value = None

          key = "Transformed "

          '
        expression: value
    to: sensor_copy
