pipelines:
  main:
    from: test_input1
    via:
    - type: outerJoin
      stream: test_input2
      valueJoiner: my_value_joiner
      timeDifference: 1s
      grace: 1s
      thisStore: left_store
      otherStore: right_store
    to: test_output
