pipelines:
  main:
    from: test_input
    via:
    - type: flatMapValues
      mapper:
        resultType: '[string]'
        expression: '[ value+''-1'',value+''-2'',value+''-3'' ]'
    to: test_output
