name: CI Build Dev Docu
on:
  push:
    branches:
      - main
      - jeroen-doc-rewrite
      - jeroen-doc-old-version
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install mike
      - name: Install include plugin
        run: pip install mkdocs-include-markdown-plugin
      - name: Install autorefs plugin
        run: pip install mkdocs-autorefs
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "deploy SNAPSHOT docs"
          git config --global user.email "ton.van.bart@axual.com"
      - name: Build Docs Site
        id: deployment
        run: |
          mike deploy --push --update-aliases 1.0.8
          mike deploy --push --update-aliases dev-branch ${{ github.ref_name }}
          mike set-default 1.0.8 --push